lr: 0.01
seed: 1
if_cuda: False
gamma: 0.5
log_dir: 'logs/logs_tau'
train_batch: 256
val_batch: 256
test_batch: 256
num_workers: 0
model_name: 'pnas-ae'
data_filepath: 'Data/data/tau_'
dataset: 'pnas'
lr_schedule: [20, 50, 100, 200]
num_gpus: 0
cpu_num: 1
pin_memory: False
in_channels: 1
input_1d_width: 3
epochs: 1000